# Generated by Django 5.0.2 on 2024-02-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Titel',
            new_name='Title',
        ),
    ]
